name: CI


on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Acuneitx Scan

        run: |

          curl -k -i --request POST --url "https://online.acunetix.com/api/v1/scans" --header "X-Auth: 1c8a29bb56641441ea8979e93c48fcd5d629fee1a86e0185523bf77d13a7192de" --header "content-type: application/json" --data '{"profile_id":"11111111-1111-1111-1111-111111111120", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"c05b3a53-7f8b-4c96-a559-978e1ccf0d64"}'
