name: CI


on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Acuneitx Scan

        run: |

          curl -k -i --request POST --url "https://ovs2.acunetix.com/api/v1/scans" --header "X-Auth: 11daef7861e4c489ca65b7cf74958a31170e8d70d140afb6cae01026d0bad60c5" --header "content-type: application/json" --data '{"profile_id":"11111111-1111-1111-1111-111111111117", "schedule":{"disable":false,"start_date":null,"time_sensitive":false}, "user_authorized_to_scan":"yes", "target_id":"4c4d686a-1a63-4bec-b5cc-61097b6aa4f0"}'
